<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>StoryForge</AssemblyName>
    <RootNamespace>StoryForge</RootNamespace>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <Version>1.20.1</Version>
    <AssemblyVersion>1.20.1</AssemblyVersion>
    <FileVersion>1.20.1</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Assets\Minecraft.ttf"/>
    <Content Include="Assets\**\*" Exclude="Assets\Minecraft.ttf" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest"/>
    <Resource Include="Assets\Minecraft.ttf"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DiscordRichPresence" Version="1.0.175"/>
  </ItemGroup>

</Project>
